name: filesystem_picker_example
description: Demonstrates how to use 'FileSystemPicker'.

version: 1.0.3

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.6.27
  permission_handler: ^5.1.0+2
  filesystem_picker_plugin:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
